
const API_URL = 'http://localhost:3000/api/v1';
const USER = {
    name: 'Pulkit Verma',
    email: 'pulkitverma2008@gmail.com',
    password: '123456'
};

const ITEMS_TO_CREATE = 15;

async function request(path: string, method: string, body?: any, token?: string) {
    const headers: any = { 'Content-Type': 'application/json' };
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const res = await fetch(`${API_URL}${path}`, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined
    });

    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw { status: res.status, data };
    return data;
}

async function seed() {
    console.log('🚀 Starting seed process...');

    let token = '';

    // 1. Try to Login or Register
    try {
        console.log('Attempting login...');
        const loginRes = await request('/auth/login', 'POST', {
            email: USER.email,
            password: USER.password
        });
        token = loginRes.data.accessToken; // Structure: { status, data: { accessToken, ... } }
        console.log('✅ Login successful');
    } catch (error: any) {
        if (error.status === 401 || error.status === 404) {
            console.log('Login failed (' + error.status + '), attempting registration...');
            try {
                const registerRes = await request('/auth/register', 'POST', USER);
                token = registerRes.data.accessToken;
                console.log('✅ Registration successful');
            } catch (regError: any) {
                console.error('❌ Registration failed:', regError.data || regError);
                return;
            }
        } else {
            console.error('❌ Login error:', error.data || error);
            // If failed, maybe try register anyway?
            try {
                console.log('Attempting registration just in case...');
                const registerRes = await request('/auth/register', 'POST', USER);
                token = registerRes.data.accessToken;
                console.log('✅ Registration successful');
            } catch (regError: any) {
                console.error('❌ Registration failed:', regError.data || regError);
                return;
            }
        }
    }

    if (!token) {
        console.error('❌ No token obtained');
        return;
    }

    // 2. Create Items
    console.log(`Creating ${ITEMS_TO_CREATE} lost items...`);

    const categories = ['Electronics', 'Books', 'Clothing', 'Accessories', 'Other'];

    for (let i = 0; i < ITEMS_TO_CREATE; i++) {
        const item = {
            title: `Lost Item #${i + 1} - ${new Date().toISOString()}`,
            description: `This is a test missing item generated by seed script. Item #${i + 1}`,
            category: categories[i % categories.length],
            status: 'LOST',
            location: 'Classroom or Canteen',
            reportedAt: new Date().toISOString()
        };

        try {
            await request('/items', 'POST', item, token);
            console.log(`✅ Created item ${i + 1}/${ITEMS_TO_CREATE}: ${item.title}`);
        } catch (error: any) {
            console.error(`❌ Failed to create item ${i + 1}:`, error.data || error);
        }

        // Small delay
        await new Promise(r => setTimeout(r, 100));
    }

    console.log('🎉 Seeding complete! User should be on top of leaderboard.');
}

seed();
